### ISSUE TITLE
Docker image for development and testing

### ISSUE THREAD

**Issue by bmpvieira** [bionode/bionode-sge#1]
We need a Docker image with [Son of Grid](https://arc.liv.ac.uk/trac/SGE) setup so that we can develop this module without the need of a HPC/cluster. @gawbul is working on one.

**Comment by gawbul** [comment]
Basic Dockerfile and requisite files are here https://github.com/gawbul/docker-sge. Have created auto-build repository in the Docker registry too https://registry.hub.docker.com/u/gawbul/docker-sge/. Can use `docker pull gawbul/docker-sge` to use. Still a couple of issues to resolve before fully functional.

**Comment by mkuzak** [comment]
@gawbul when I try to pull the image I get:
2014/12/10 02:23:20 Tag latest not found in repository gawbul/docker-sge

**Comment by gawbul** [comment]
Probably still building? Only just pushed to the repo! Will check...

**Comment by gawbul** [comment]
Yeah, still building https://registry.hub.docker.com/u/gawbul/docker-sge/builds_history/96056/.

**Comment by gawbul** [comment]
Just about sorted the issues and got SGE to auto install. Having a problem with the hostname changing during the build so get an error in resolving the hostname (see https://github.com/gawbul/docker-sge/issues/3).

**Comment by gawbul** [comment]
Should all be working now https://github.com/gawbul/docker-sge :)

**Comment by gawbul** [comment]
@bmpvieira @mkuzak I've been thinking about the container configuration and wanted to get your thoughts. Currently I am installing SGE and configuring the container as the master, exec, and submission host. This is how every container you spin up using the Docker image will be configured.

Should I change it so SGE is compiled from the Dockerfile, but then the user can run one of a number of shell scripts from within the container to setup SGE how they prefer? It would still require some manual input of hostnames I think, though, it would be useful to do service discovery (perhaps using consul? https://www.consul.io/) to automate the configuration of that too. Would still probably need some container linking though?

**Comment by mkuzak** [comment]
I think the current configuration is good for start. The simpler the setup the better. Can get more complicated in the future.

**Comment by gawbul** [comment]
@mkuzak Good stuff, thanks! Just sorting a couple of minor config issues with the image. Hopefully fully functional by the end of the day?

**Comment by gawbul** [comment]
@mkuzak @bmpvieira Fixed image - just building/pushing to Docker Hub. See README at https://github.com/gawbul/docker-sge for information on how to run.

**Comment by bmpvieira** [comment]
Thanks a lot @gawbul!
Seems to be working as `qstat` shows jobs in queue, however it also tells me I'm not allowed to run jobs (confusing).

``` bash
sgeadmin@084311c933c3:~$ echo "echo Running test from $HOSTNAME" | qsub
Unable to run job: warning: sgeadmin's job is not allowed to run in any queue
Your job 2 ("STDIN") has been submitted
Exiting.
sgeadmin@084311c933c3:~$ qstat
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
      1 0.55500 STDIN      sgeadmin     qw    04/04/2015 15:50:07                                    1
```

Now we just need to actually write the wrapper :laughing: #2
